<style>
.container{
    text-align:left;
    margin-left:15%;
    margin-right:15%;
    margin-bottom:20px;
    margin-top:20px;
    background-color: #f5f5f5 !important;
    font-family:Bookman, UWC;
}
body{
  background-color:#f5f5f5;
}
.author{
    text-align: right !important;
}
.list-group-item{
  background-color:#f5f5f5
}
</style>

<svelte:head>
    <title>Reviews - Kerpel Law</title>
</svelte:head>
<body>
<div class="container">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">From the beginning, David set himself apart as a sincere, efficient and very effective attorney. After first time consults with other attorneys, I realized during my first meeting with David that he had educated me on the issues and aspects of the law that had a significant impact on how I proceeded with the divorce process. He strongly recommended mediation, which other attorneys did not, showing he is not about the money but rather the client. I felt that David always had me, and my children's best interests, at the forefront. His continued counsel and guidance through the mediation process empowered me to be a better negotiator on my behalf.<br><br>David was always quick to respond when several 'urgent' issues developed. He is clearly a very hard worker for his clients. I will be using David should any other issues arise and I would strongly recommend him to anyone in need of divorce representation. Thanks David!<br><br><div class = "author"> - R.W.  </div></li>
    <li class="list-group-item">Most people call him David. I call him Superman.<br><br>When the frustration with my former spouse's lack of compliance with out Marital Settlement Agreement reached a point that I could not tolerate, I searched for a new family law attorney. I had been divorced for five years and had been around the block with lawyers and the Lake County court system. This time I understood what I needed in an attorney. He/she had to be someone who understood the issues problematic in my case, as well as the skill and experience to deal with the underhanded tactics of the opposing attorney.<br><br>From the start, David took my primary concern seriously, but asked permission to look further into problems I did not have the energy or the will to fight anymore. He did this out of concern for me and because of his keen powers of observation- not for his personal financial gain.<br><br>Over the next 18 months, I learned that my attorney was really a Superman. He revealed his 'secret identity' as he dealt with 'Lex Luther' diplomatically and strategically. He did not let the opposing attorney sidetrack him with stall tactics and an uncooperative demeanor. He stayed focused on the end goal- what was just and fair. Superman's legal expertise and determination won an outstanding settlement for me. And, because David set up safety nets, the Marital Settlement Agreement is now being followed by my ex. David is truly a hero to me!<br><br><div class = "author">- C.C.  </div></li>
    <li class="list-group-item">There are not enough words to express the fact how much you did for me and for my family. During this divorce process, you were able to preserve my well-being. For me, the purpose of my life is to be with my son all the time, and you were able to achieve the best possible outcome from this divorce case. I knew how difficult it was to accomplish this, and you were able to accomplish it. Your support was clear from the very first day you met me and listened to my sad story of my marriage. Your support during this terrible year, is the best around. Nobody I know could even imagine that my lawyer could do so much for me. You did it. You are energetic and professional in your business. I have no hesitation in recommending you to my friends if they ever need help! A huge thank you from the bottom of my heart. A huge thank you from all of my family! Thank you for being around in that terrible time for me.<br><br><div class = "author">- R.I. </div></li>
    <li class="list-group-item">David represented me in a very adversarial, litigious and lengthy divorce. With his expert knowledge of Family Law, his excellent communication skills, high level of integrity and compassion, he guided me through a very difficult time. Throughout the case, he stayed focused, persistent and reassuring. David hung in there when most lawyers would have walked away. This is simply a fact. His loyalty is without exception.<br><br>David possesses the unique qualities of purpose along with a genuine compassion for families. His tenacious spirit, creativity, resourcefulness, and his unwavering determination to get me the best possible outcome was just outstanding. David helps bring dignity to an undignified process. His character speaks to not only his intelligence, but also to his humanity. Without his support, resolve and proficient knowledge of the law, I am certain that I would still be stuck in an abusive situation.<br><br>Anyone who finds themselves in a seemingly impossible circumstance involving Family Law would be well-served and fortunate to have David Kerpel on their side. David is someone who you want to know and continue to know even after the dissolution is finalized. He goes above and beyond the call of duty. I cannot thank David enough for staying the course and for helping us through this extremely difficult time.<br><br><div class = "author">- M.A.    </div></li>
    <li class="list-group-item">David-<br><br>I want to thank you for representing me in my divorce. I especially want you to know that I appreciate you trying to look out for the best interest of my daughters and I. The issues that were involved in separating myself from my husband were very complicated and you always made me feel like you understood them and did not hesitate to seek out additional guidance if you did not.<br><br><div class = "author">- J.G. </div></li>
    <li class="list-group-item">We were two years into a case that seemed to be going nowhere, when we switched lawyers to David.  At my most cynical of  times, David made me a believer. He immediately made a difference, not only in the court room but out of it also.  David was more than willing to talk to us at any time, returned our calls promptly, and made us feel like we mattered.<br><br>David is intelligent, dependable, creative, and to us his strongest attribute is his loyalty. His stick-to-itiveness has been incredible. He has stuck with our case when most would not have. Not only has he stuck around;  he has rectified all of the issues in a timely manner in our favor.<br><br>I would, and do recommend him to anyone that I meet in need of a lawyer. If you are looking for a lawyer that possesses all of the qualities we mentioned above, David Kerpel is your man. He is a lawyer because he loves to help, not for the paycheck.<br><br>David has become more than "our lawyer," he is a family friend.<br><br><div class = "author">- K & K.  B.  </div></li>
    <li class="list-group-item">David is one of the sharpest lawyers I have worked with. He fought hard to get a fair resolution of the custody and financial issues in my divorce. He ably defended me in a three year divorce case. His legal skill means I get to see my sons regularly with more access than most fathers get in a contested custody case. Perhaps the best compliment is that my ex-wife believes that the divorce court must favor fathers because David prevailed on most disputed issues in our case.<br><br><div class = "author">- D. W.  </div></li>
    <li class="list-group-item">I was involved in a bitter dispute over child support. I found David, and he managed to deal with a lot of the extremely difficult issues I had been dealing with for nearly 8 years. He managed an approach with my ex that was direct and to the point. He got him to pay portions of an extremely large arrearage on his child support payments. When we needed to get tough, he had a warrant for his arrest issued and expedited. After that, I settled on 85% of what I was owed knowing full well that I probably would have never received a dime had David not been calm and direct with my ex in this case, which was not an easy task. As a result of David's persistent efforts, my daughter walked away with her college account paid in full, and money to buy a home when she gets old enough.<br><br><div class = "author">- E. K.  </div></li>
    <li class="list-group-item">David was clear, responsive, and supportive, everything I was looking for in an attorney. He is an excellent communicator and listened to my needs at every step along the way. David made what could've been a difficult situation much easier to navigate. I am so thankful to have found him!<br><br><div class = "author">- E. J.   </div></li>
    <li class="list-group-item">David, thank you so very much for fighting for my kids. They are safe today because of your efforts. I can't thank you enough.<br><br>Thank you not only for helping me gain custody of my children, but thank you for helping me retain custody in a tough fight.<br><br><div class = "author">- G. M. </div></li>
    <li class="list-group-item">I was in an abusive relationship with my husband and needed someone to protect me and my child. Physically moving away from California to Chicago did not stop the violent threats from my ex-husband. David helped protect me and my daughter. He instantly got us an Order of Protection in a difficult situation. David worked with me all the way until I was assured that my daughter and I were secure in every aspect of our lives.<br><br><div class = "author">- A. S. </div></li>
    <li class="list-group-item">David's confidence provided me with the assurance that my case would be handled to the best of my interests. His interpersonal style made working with him on this unpleasant task very easy. David brought a good sense of humor to discussions, which also helped relieve tensions. When required, David was aggressive with opposing counsel, but never combative to the point where negotiations broke down. My case stretched on forever, but David remained patient with me while at the same time pushing the opposing party for timely closure. I confidently recommend David's services to anyone in need of legal counsel in the area of divorce law.<br><br><div class = "author">- G. R.    </div></li>
    <li class="list-group-item">David picked up my case at a very difficult time and walked me through several potential landmines with enthusiasm and a good degree of creativity. Contrary to prior experience in the Lake County Family Court system, I truly felt like I had someone who was on my side and not just doing their job. I have, and will continue to recommend David to anyone unfortunate enough to require a family law attorney.<br><br><div class = "author">- V. A.  </div></li>
    <li class="list-group-item">Simply put David Kerpel is a first class Attorney. Not only is he thorough and intelligent but he sincerely made me feel "safe" at a time when there was no one I could trust! He is one hard working Lawyer! One thing is very clear, David isn't in this field for the money. He cares. That is very important!<br><br>I have no living family, and I am disabled. For me Divorce & freedom meant having a very different life. David helped me find information on housing and financial assistance, and more, so I could have a chance to rebuild my life after my divorce. Not many Divorce Attorney's will take the time to go that far for their clients.<br><br><div class = "author">- A. M.   </div></li>
  </ul>
</div>
</body>